name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          REPO_NAME_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          FULL_IMAGE="${REPO_NAME_LC}:${IMAGE_TAG}"
          LATEST_IMAGE="${REPO_NAME_LC}:latest"

          echo "Building images: $FULL_IMAGE and $LATEST_IMAGE"
          docker build -t "$FULL_IMAGE" -t "$LATEST_IMAGE" .

          # Use a temporary var so agent doesn't nuke it later
          echo "BUILT_IMAGE=$FULL_IMAGE" >> $GITHUB_ENV
          echo "BUILT_IMAGE_LATEST=$LATEST_IMAGE" >> $GITHUB_ENV
          echo "GIT_REF=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: FacetsCTL Integration
        run: |
          if command -v curl >/dev/null 2>&1 && command -v bash >/dev/null 2>&1; then
            echo "curl/bash present"
          fi
          curl -sSL https://facets-cloud.github.io/facets-schemas/scripts/fctl_install.sh | bash && source ~/.bashrc
          if ! command -v fctl &> /dev/null; then echo "fctl not found on PATH"; fi
          echo "TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_URL=$BUILT_IMAGE" >> $GITHUB_ENV
          echo "GIT_REF=${GIT_REF}" >> $GITHUB_ENV
          curl -s https://facets-cloud.github.io/facets-schemas/scripts/fctl_register.sh | bash -s -- \
            -u "himanshu.mahto@facets.cloud" \
            -c "https://facetsdemo.console.facets.cloud" \
            -p "pet-clinic-satyendra" \
            -s "testing-ai" \
            -a "rohit-ecr" \
            -i "true"
