name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          IMAGE_NAME=my-app
          BUILD_TAG=${GITHUB_SHA::8}
          IMAGE_TAG="${IMAGE_NAME}:${BUILD_TAG}"
          docker build -t "${IMAGE_TAG}" .

      - name: Prepare environment for FacetsCTL
        run: |
          if command -v curl >/dev/null 2>&1 && command -v bash >/dev/null 2>&1; then echo "curl/bash present"; else sudo apt-get update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq bash curl ca-certificates; fi

      - name: Install FacetsCTL
        run: |
          curl -sSL https://facets-cloud.github.io/facets-schemas/scripts/fctl_install.sh | bash && source ~/.bashrc
          if ! command -v fctl &> /dev/null; then echo "fctl not found on PATH"; fi

      - name: Set TOKEN environment variable
        run: echo "TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV

      - name: Set DOCKER_IMAGE_URL and GIT_REF
        run: |
          IMAGE_NAME=my-app
          BUILD_TAG=${GITHUB_SHA::8}
          DOCKER_IMAGE_URL="rohit-ecr/${IMAGE_NAME}:${BUILD_TAG}"
          echo "DOCKER_IMAGE_URL=${DOCKER_IMAGE_URL}" >> $GITHUB_ENV
          GIT_REF=${GITHUB_REF##*/}
          echo "GIT_REF=${GIT_REF}" >> $GITHUB_ENV

      - name: Register Docker image with FacetsCTL
        run: |
          curl -s https://facets-cloud.github.io/facets-schemas/scripts/fctl_register.sh | bash -s -- \
            -u "himanshu.mahto@facets.cloud" \
            -c "https://facetsdemo.console.facets.cloud" \
            -p "pet-clinic-satyendra" \
            -s "testing-ai" \
            -a "rohit-ecr" \
            -i "true"
